gitRepoUrl = "https://github.com/wiindsom/Structix"
gitSourceBranch = "main"

[home]
enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Fully Open Source Under The MIT License."

[docusaurus]
title = "Structix"
tagline = "A Data Structure Library For Roblox."
