gitRepoUrl = "https://github.com/wiindsom/Structix"
gitSourceBranch = "main"

[home]
enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright © 2025 wiindsom. Licensed under the MIT License."
