gitRepoUrl = "https://github.com/wiindsom/Structix"
gitSourceBranch = "main"

[home]
enabled = true
includeReadme = false

[docusaurus]
tagline = "A Data Structure Library For Roblox."


[footer]
style = "dark"
copyright = "Copyright © 2025 wiindsom. Licensed under the [MIT License](https://opensource.org/licenses/MIT)"
