gitRepoUrl = "https://github.com/wiindsom/Structix"
gitSourceBranch = "main"

[home]
enabled = true
includeReadme = true

[[home.features]]
title = "Something"
description = "yuh"

[docusaurus]
tagline = "A Data Structure Library For Roblox."